[source]
excludes = [
  "**/vendor/**",
  "**/node_modules/**",
  "**/.git/**",
  "**/wp-admin/**",
  "**/wp-includes/**",
  "**/wp-content/uploads/**",
]
extensions = ["php", "phtml"]

[parser]
enable-short-tags = false

[formatter]
first-method-chain-on-new-line = true
method-chain-breaking-style = "next-line"
null-type-hint = "null_pipe_last"
preserve-breaking-member-access-chain = true
print-width = 145

[linter]
excludes = [
  "**/*.php.html",
]
